drop table user_info if exists;

--用户信息表
create table user_info
(
    id       integer GENERATED BY DEFAULT AS IDENTITY (START WITH 6) NOT NULL PRIMARY KEY,
    username varchar(32)                                             NOT NULL,
    password varchar(32) DEFAULT '12345678',
    usertype varchar(2),
    enabled  integer,
    realname varchar(50),
    qq       varchar(12),
    email    varchar(100),
    address  varchar(200),
    tel      varchar(30)
);

insert into user_info (id, username, password, usertype)
values (1, 'test1', '12345678', '1');
insert into user_info (id, username, password, usertype)
values (2, 'test2', 'aaaa', '2');
insert into user_info (id, username, password, usertype)
values (3, 'test3', 'bbbb', '1');
insert into user_info (id, username, password, usertype)
values (4, 'test4', 'cccc', '2');
insert into user_info (id, username, password, usertype)
values (5, 'test5', 'dddd', '1');